import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

export const translations = {
  de: {
    nav: {
      how: 'Wie es funktioniert',
      subjects: 'Fächer',
      aiFeedback: 'Levi',
      faq: 'FAQ',
      signIn: 'Anmelden',
    },
    hero: {
      h1a: 'Schreib. Lern.',
      h1b: 'Besteh.',
      sub: 'Übe ZP10-Aufgaben und bekomm ehrliches Feedback von Levi – deinem persönlichen Lerncoach, der genau weiß, wie ZP10 bewertet wird.',
      cta: 'Jetzt kostenlos starten →',
      learnMore: 'Mehr erfahren',
      demoTask: 'Deutsch · Argumentation · Aufgabe 2',
      demoStatus: 'Levi hat ausgewertet',
      demoTagThesis: '✓ Klare These',
      demoTagEvidence: '✓ Textstellen belegt',
      demoTagCounter: '↑ Gegenpositionen fehlen',
    },
    how: {
      label: 'Ablauf',
      title: 'In drei Schritten zur besseren Note',
      sub: 'Kein Auswendiglernen. Kein raten. Echtes Feedback auf deine Antworten.',
      s1title: 'Aufgabe bearbeiten',
      s1text: 'Wähle ein Fach und eine prüfungsnahe Aufgabe. Schreib deine Antwort direkt in die App – genau wie in der echten Prüfung.',
      s2title: 'KI bewertet deine Lösung',
      s2text: 'Unsere KI vergleicht deine Antwort mit dem echten Bewertungsraster der ZP10 und gibt dir eine Punktzahl – transparent und nachvollziehbar.',
      s3title: 'Gezielt verbessern',
      s3text: 'Du siehst genau, wo du gut bist und was dir noch fehlt. Mit jeder Übung wird das Feedback präziser – dein Fortschritt wird langfristig verfolgt.',
    },
    subjects: {
      label: 'Fächer',
      title: 'Alle drei ZP10-Fächer',
      sub: 'Für Gymnasium, Realschule und Hauptschule – mit angepassten Aufgaben je nach Prüfungsprofil.',
      deSub: 'Texte analysieren, argumentieren, Stellung nehmen – mit individuellem Feedback zu Struktur, Belegen und Sprache.',
      mathSub: 'Funktionen, Geometrie, Wahrscheinlichkeit – schrittweise Lösungshilfen und Erklärungen zu jedem Rechenweg.',
      enSub: 'Reading, Listening, Comment – Feedback auf deine englischen Texte inklusive Grammatik- und Vokabelhinweisen.',
    },
    ki: {
      label: 'Dein Lerncoach',
      title: 'Levi kennt ZP10 in- und auswendig.',
      sub: 'Kein Warten auf den Lehrer. Levi liest deine Antwort, bewertet sie nach dem echten ZP10-Raster und sagt dir genau, was noch fehlt.',
      f1title: 'Echte Punktebewertung',
      f1text: 'Levi bewertet nach dem offiziellen ZP10-Bewertungsraster – transparent, nachvollziehbar, keine Blackbox.',
      f2title: 'Stärken & Schwächen',
      f2text: 'Du siehst genau, was gut war und was du beim nächsten Mal besser machen kannst – konkret, nicht vage.',
      f3title: 'Fortschritt über Zeit',
      f3text: 'Levi merkt sich, wie du dich entwickelst – und zeigt dir, wo du dich wirklich verbessert hast.',
      mockContent: '»Ich finde, soziale Medien sollten für Jugendliche eingeschränkt werden, weil sie süchtig machen und das Selbstbild negativ beeinflussen.«',
      mockLabel1: 'Inhalt & Argumentation',
      mockLabel2: 'Sprachliche Qualität',
      mockFeedback: '✓ These klar formuliert · Belege konkret\n↑ Gegenposition fehlt – zeige auch die andere Seite',
    },
    faq: {
      label: 'FAQ',
      title: 'Häufige Fragen',
      q1: 'Für welche Schulformen ist die App geeignet?',
      a1: 'Aktuell unterstützt ZP10 Trainer Gymnasium (GYM), Realschule (MSA) und Hauptschule (EESA). Weitere Schulformen wie Gesamtschule und Sekundarschule werden in Kürze hinzugefügt.',
      q2: 'Sind die Aufgaben echte ZP10-Prüfungsaufgaben?',
      a2: 'Nein – wir erstellen eigene Aufgaben im ZP10-Stil, um urheberrechtliche Probleme zu vermeiden. Die Aufgaben orientieren sich aber eng am Format, den Themen und den Bewertungskriterien der offiziellen Prüfungen.',
      q3: 'Wie funktioniert die KI-Bewertung genau?',
      a3: 'Deine Antwort wird zusammen mit der Aufgabenstellung, einer Musterlösung und dem offiziellen Bewertungsraster an ein KI-Modell gesendet. Das Modell vergibt Punkte und begründet jede Entscheidung – transparent und nachvollziehbar.',
      q4: 'Ist die App kostenlos?',
      a4: 'In der aktuellen Beta-Phase ist ZP10 Trainer kostenlos nutzbar. Registriere dich jetzt und erhalte kostenlosen Zugang zu allen Übungsaufgaben und KI-Feedback.',
      q5: 'Werden meine Daten gespeichert?',
      a5: 'Ja – um deinen Lernfortschritt zu verfolgen, werden deine Antworten und Ergebnisse in deinem Konto gespeichert. Alle Daten werden sicher in der EU gehostet und nicht an Dritte weitergegeben.',
    },
    auth: {
      signIn: 'Anmelden',
      signUp: 'Registrieren',
      withGoogle: 'Mit Google fortfahren',
      withApple: 'Mit Apple fortfahren',
      orEmail: 'oder per E-Mail',
      email: 'E-Mail-Adresse',
      password: 'Passwort',
      firstName: 'Vorname',
      schoolType: 'Schulform',
      schoolPlaceholder: 'Bitte wählen...',
      gym: 'Gymnasium (GYM)',
      msa: 'Realschule (MSA)',
      eesa: 'Hauptschule (EESA)',
      submitSignIn: 'Anmelden',
      submitSignUp: 'Konto erstellen',
      noAccount: 'Noch kein Konto?',
      signUpLink: 'Jetzt registrieren',
      hasAccount: 'Bereits registriert?',
      signInLink: 'Anmelden',
    },
    footer: {
      tagline: 'KI-gestützte ZP10-Vorbereitung für NRW.',
      appCol: 'App',
      legalCol: 'Rechtliches',
      privacy: 'Datenschutz',
      imprint: 'Impressum',
      terms: 'Nutzungsbedingungen',
      copy: '© 2026 ZP10 Trainer. Alle Rechte vorbehalten.',
      disclaimer: 'Nicht offiziell mit dem Land NRW verbunden.',
    },
  },
  en: {
    nav: {
      how: 'How it works',
      subjects: 'Subjects',
      aiFeedback: 'Levi',
      faq: 'FAQ',
      signIn: 'Sign in',
    },
    hero: {
      h1a: 'Write. Learn.',
      h1b: 'Pass.',
      sub: 'Practice ZP10 tasks and get honest feedback from Levi – your personal learning coach who knows exactly how ZP10 is graded.',
      cta: 'Get started for free →',
      learnMore: 'Learn more',
      demoTask: 'German · Argumentation · Task 2',
      demoStatus: 'Levi has evaluated',
      demoTagThesis: '✓ Clear thesis',
      demoTagEvidence: '✓ Text evidence used',
      demoTagCounter: '↑ Counter-arguments missing',
    },
    how: {
      label: 'Process',
      title: 'Three steps to a better grade',
      sub: 'No memorizing. No guessing. Real feedback on your answers.',
      s1title: 'Work on a task',
      s1text: 'Choose a subject and an exam-style task. Write your answer directly in the app – just like in the real exam.',
      s2title: 'AI evaluates your answer',
      s2text: 'Our AI compares your answer to the official ZP10 grading rubric and gives you a score – transparent and traceable.',
      s3title: 'Improve strategically',
      s3text: 'You see exactly where you\'re strong and what\'s missing. With each practice session, feedback gets sharper – your progress is tracked long-term.',
    },
    subjects: {
      label: 'Subjects',
      title: 'All three ZP10 subjects',
      sub: 'For Gymnasium, Realschule, and Hauptschule – with tasks adapted to your exam profile.',
      deSub: 'Analyze texts, argue, take a stance – with individual feedback on structure, evidence, and language.',
      mathSub: 'Functions, geometry, probability – step-by-step hints and explanations for every calculation path.',
      enSub: 'Reading, Listening, Comment – feedback on your English texts including grammar and vocabulary tips.',
    },
    ki: {
      label: 'Your learning coach',
      title: 'Levi knows ZP10 inside out.',
      sub: 'No waiting for your teacher. Levi reads your answer, grades it using the real ZP10 rubric, and tells you exactly what\'s missing.',
      f1title: 'Real point scoring',
      f1text: 'Levi grades based on the official ZP10 rubric – transparent, traceable, no black box.',
      f2title: 'Strengths & weaknesses',
      f2text: 'You see exactly what worked and what to do better next time – specific, never vague.',
      f3title: 'Progress over time',
      f3text: 'Levi tracks how you develop – and shows you where you\'ve genuinely improved.',
      mockContent: '»I think social media should be restricted for teens because it creates addiction and negatively affects self-image.«',
      mockLabel1: 'Content & argumentation',
      mockLabel2: 'Language quality',
      mockFeedback: '✓ Thesis clearly stated · Evidence concrete\n↑ Counter-argument missing – show the other side too',
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently asked questions',
      q1: 'Which school types is the app for?',
      a1: 'Currently ZP10 Trainer supports Gymnasium (GYM), Realschule (MSA), and Hauptschule (EESA). More school types like Gesamtschule and Sekundarschule are coming soon.',
      q2: 'Are the tasks real ZP10 exam questions?',
      a2: 'No – we create our own ZP10-style tasks to avoid copyright issues. However, they closely follow the format, topics, and grading criteria of the official exams.',
      q3: 'How exactly does the AI grading work?',
      a3: 'Your answer is sent to an AI model along with the task, a model answer, and the official grading rubric. The model awards points and justifies every decision – transparently and traceably.',
      q4: 'Is the app free?',
      a4: 'During the current beta phase, ZP10 Trainer is free to use. Sign up now and get free access to all practice tasks and AI feedback.',
      q5: 'Is my data stored?',
      a5: 'Yes – to track your learning progress, your answers and results are saved in your account. All data is securely hosted in the EU and not shared with third parties.',
    },
    auth: {
      signIn: 'Sign in',
      signUp: 'Sign up',
      withGoogle: 'Continue with Google',
      withApple: 'Continue with Apple',
      orEmail: 'or with email',
      email: 'Email address',
      password: 'Password',
      firstName: 'First name',
      schoolType: 'School type',
      schoolPlaceholder: 'Please select...',
      gym: 'Gymnasium (GYM)',
      msa: 'Realschule (MSA)',
      eesa: 'Hauptschule (EESA)',
      submitSignIn: 'Sign in',
      submitSignUp: 'Create account',
      noAccount: 'No account yet?',
      signUpLink: 'Sign up now',
      hasAccount: 'Already have an account?',
      signInLink: 'Sign in',
    },
    footer: {
      tagline: 'AI-powered ZP10 prep for NRW.',
      appCol: 'App',
      legalCol: 'Legal',
      privacy: 'Privacy policy',
      imprint: 'Imprint',
      terms: 'Terms of use',
      copy: '© 2026 ZP10 Trainer. All rights reserved.',
      disclaimer: 'Not officially affiliated with the state of NRW.',
    },
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('de')
  const t = translations[lang]
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
