import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

export const translations = {
  de: {
    nav: {
      how: 'Wie es funktioniert',
      subjects: 'Fächer',
      aiFeedback: 'Zeno',
      faq: 'FAQ',
      signIn: 'Anmelden',
      themeToggle: 'Darkmode umschalten',
    },
    hero: {
      h1a: 'Schreib. Lern.',
      h1b: 'Besteh.',
      sub: 'Übe ZP10-Aufgaben und bekomm ehrliches Feedback von Zeno – deinem persönlichen Lerncoach, der genau weiß, wie ZP10 bewertet wird.',
      cta: 'Jetzt kostenlos starten →',
      learnMore: 'Mehr erfahren',
      demoTask: 'Deutsch · Argumentation · Aufgabe 2',
      demoStatus: 'Zeno hat ausgewertet',
      demoTagThesis: '✓ Klare These',
      demoTagEvidence: '✓ Textstellen belegt',
      demoTagCounter: '↑ Gegenpositionen fehlen',
    },
    how: {
      label: 'Ablauf',
      title: 'In drei Schritten zur besseren Note',
      sub: 'Kein Auswendiglernen. Kein raten. Echtes Feedback auf deine Antworten.',
      s1title: 'Aufgabe bearbeiten',
      s1text: 'Wähle ein Fach und eine prüfungsnahe Aufgabe. Schreib deine Antwort direkt in die App – genau wie in der echten Prüfung.',
      s2title: 'KI bewertet deine Lösung',
      s2text: 'Unsere KI vergleicht deine Antwort mit dem echten Bewertungsraster der ZP10 und gibt dir eine Punktzahl – transparent und nachvollziehbar.',
      s3title: 'Gezielt verbessern',
      s3text: 'Du siehst genau, wo du gut bist und was dir noch fehlt. Mit jeder Übung wird das Feedback präziser – dein Fortschritt wird langfristig verfolgt.',
    },
    subjects: {
      label: 'Fächer',
      title: 'Alle drei ZP10-Fächer',
      sub: 'Für Gymnasium, Realschule und Hauptschule – mit angepassten Aufgaben je nach Prüfungsprofil.',
      deSub: 'Texte analysieren, argumentieren, Stellung nehmen – mit individuellem Feedback zu Struktur, Belegen und Sprache.',
      mathSub: 'Funktionen, Geometrie, Wahrscheinlichkeit – schrittweise Lösungshilfen und Erklärungen zu jedem Rechenweg.',
      enSub: 'Reading, Listening, Comment – Feedback auf deine englischen Texte inklusive Grammatik- und Vokabelhinweisen.',
    },
    ki: {
      label: 'Dein Lerncoach',
      title: 'Zeno kennt ZP10 in- und auswendig.',
      sub: 'Kein Warten auf den Lehrer. Zeno liest deine Antwort, bewertet sie nach dem echten ZP10-Raster und sagt dir genau, was noch fehlt.',
      f1title: 'Echte Punktebewertung',
      f1text: 'Zeno bewertet nach dem offiziellen ZP10-Bewertungsraster – transparent, nachvollziehbar, keine Blackbox.',
      f2title: 'Stärken & Schwächen',
      f2text: 'Du siehst genau, was gut war und was du beim nächsten Mal besser machen kannst – konkret, nicht vage.',
      f3title: 'Fortschritt über Zeit',
      f3text: 'Zeno merkt sich, wie du dich entwickelst – und zeigt dir, wo du dich wirklich verbessert hast.',
      mockContent: '»Ich finde, soziale Medien sollten für Jugendliche eingeschränkt werden, weil sie süchtig machen und das Selbstbild negativ beeinflussen.«',
      mockLabel1: 'Inhalt & Argumentation',
      mockLabel2: 'Sprachliche Qualität',
      mockFeedback: '✓ These klar formuliert · Belege konkret\n↑ Gegenposition fehlt – zeige auch die andere Seite',
    },
    faq: {
      label: 'FAQ',
      title: 'Häufige Fragen',
      q1: 'Für welche Schulformen ist die App geeignet?',
      a1: 'Aktuell unterstützt ZP10 Trainer Gymnasium (GYM), Realschule (MSA) und Hauptschule (EESA). Weitere Schulformen wie Gesamtschule und Sekundarschule werden in Kürze hinzugefügt.',
      q2: 'Sind die Aufgaben echte ZP10-Prüfungsaufgaben?',
      a2: 'Nein – wir erstellen eigene Aufgaben im ZP10-Stil, um urheberrechtliche Probleme zu vermeiden. Die Aufgaben orientieren sich aber eng am Format, den Themen und den Bewertungskriterien der echten Prüfungen.',
      q3: 'Wie funktioniert die KI-Bewertung genau?',
      a3: 'Deine Antwort wird zusammen mit der Aufgabenstellung, einer Musterlösung und dem offiziellen Bewertungsraster an ein KI-Modell gesendet. Das Modell vergibt Punkte und begründet jede Entscheidung – transparent und nachvollziehbar.',
      q4: 'Ist die App kostenlos?',
      a4: 'In der aktuellen Beta-Phase ist ZP10 Trainer kostenlos nutzbar. Registriere dich jetzt und erhalte kostenlosen Zugang zu allen Übungsaufgaben und KI-Feedback.',
      q5: 'Werden meine Daten gespeichert?',
      a5: 'Ja – um deinen Lernfortschritt zu verfolgen, werden deine Antworten und Ergebnisse in deinem Konto gespeichert. Alle Daten werden sicher in der EU gehostet und nicht an Dritte weitergegeben.',
    },
    auth: {
      signIn: 'Anmelden',
      signUp: 'Registrieren',
      email: 'E-Mail-Adresse',
      password: 'Passwort',
      firstName: 'Vorname',
      schoolType: 'Schulform',
      schoolPlaceholder: 'Bitte wählen...',
      gym: 'Gymnasium (GYM)',
      msa: 'Realschule (MSA)',
      eesa: 'Hauptschule (EESA)',
      submitSignIn: 'Anmelden',
      submitSignUp: 'Konto erstellen',
      noAccount: 'Noch kein Konto?',
      signUpLink: 'Jetzt registrieren',
      hasAccount: 'Bereits registriert?',
      signInLink: 'Anmelden',
      confirmEmailMessage: 'Bitte bestätige deine E-Mail! Überprüfe dein Postfach und klicke auf den Bestätigungslink.',
      goToDashboard: 'Zum Dashboard',
      goToLogin: 'Zum Login',
      forgotPassword: 'Passwort vergessen?',
      forgotPasswordHint: 'Gib deine E-Mail ein, um einen Reset-Link zu erhalten.',
      resetPasswordHint: 'Wenn du über den E-Mail-Link hier gelandet bist, setze jetzt ein neues Passwort.',
      sendResetMail: 'Reset-E-Mail senden',
      resetMailSent: 'E-Mail versendet. Prüfe dein Postfach.',
      resetEmailRequired: 'Bitte gib zuerst deine E-Mail-Adresse ein.',
      linkExpired: 'Der Bestätigungslink ist abgelaufen. Bitte registriere dich erneut.',
      linkError: 'Der Bestätigungslink konnte nicht verarbeitet werden. Bitte versuche es erneut.',
      linkErrorGeneric: 'Bei der E-Mail-Bestätigung ist ein Fehler aufgetreten.',
      close: 'Schließen',
    },
    footer: {
      tagline: 'KI-gestützte ZP10-Vorbereitung für NRW.',
      appCol: 'App',
      legalCol: 'Rechtliches',
      privacy: 'Datenschutz',
      imprint: 'Impressum',
      terms: 'Nutzungsbedingungen',
      copy: '© 2026 ZP10 Trainer. Alle Rechte vorbehalten.',
      disclaimer: 'Nicht offiziell mit dem Land NRW verbunden.',
    },
    dashboard: {
      greeting: 'Hallo',
      subtitle: 'Bereit für deine ZP10-Vorbereitung?',
      signOut: 'Abmelden',
      fallbackName: 'Lernende:r',
      klasseFallback: 'Klasse 10',
      nextExam: 'Nächste Prüfung',
      daysUnit: 'Tage',
      examsCompleted: 'Prüfungen abgeschlossen ✓',
      overallProgress: 'Gesamtfortschritt',
      subjects: 'Fächer',
      examOverview: 'Prüfungsübersicht',
      lastActivity: 'Zuletzt geöffnet',
      noActivity: 'Noch keine Aktivität',
      emailNotConfirmed: 'Bitte bestätige deine E-Mail-Adresse, um auf alle Inhalte zuzugreifen.',
      emailNotConfirmedHint: 'Wir haben dir eine Bestätigungs-E-Mail geschickt. Prüfe auch deinen Spam-Ordner.',
      resendEmail: 'Bestätigungs-E-Mail erneut senden',
      emailResent: 'E-Mail wurde erneut gesendet!',
      emailResendFailed: 'Die Bestätigungs-E-Mail konnte nicht erneut gesendet werden. Bitte versuche es noch einmal.',
      contentLocked: 'Bestätige deine E-Mail, um diese Inhalte freizuschalten.',
      quickOverviewTitle: 'Übersicht',
      quickOverviewDescription: 'Wichtige Kennzahlen für deinen aktuellen Lernstand.',
      subjectsDescription: 'Wähle ein Fach und setze dein Training gezielt fort.',
      zenoDescription: 'Starte deinen ZP10-Chat mit Zeno, lade Aufgaben hoch und trainiere mit strukturiertem Feedback.',
      zenoHighlights: 'Erhalte konkrete Hinweise zu Argumentation, Sprache und Struktur – direkt im Chat.',
      detailsTitle: 'Details',
      detailsDescription: 'Prüfungsplanung und letzter Lernkontext auf einen Blick.',
      gotoZenoInsights: 'Zu Zeno Insights',
      learningThisWeek: 'Lernzeit diese Woche',
      currentStreak: 'Aktuelle Streak',
      totalSessions: 'Gesamte Sessions',
      totalLearningTime: 'Gesamte Lernzeit',
      weeklyActivityTitle: 'Wochenaktivität',
      weeklyActivityDescription: 'Dein Fortschritt in den letzten 7 Tagen basierend auf deinen Lernsessions.',
      weeklyChartAria: 'Lernzeit in Minuten pro Tag',
      recentSessionsTitle: 'Letzte Lernsessions',
      recentSessionsDescription: 'Zuletzt eingetragene Lernsessions aus deiner Historie.',
      focusTitle: 'Lernfokus',
      focusDescription: 'Wo du aktuell die meiste Lernzeit investierst.',
      noSessionData: 'Noch keine Lernsessions eingetragen.',
      noWeeklySessions: 'Diese Woche wurde noch keine Lernsession eingetragen.',
      noFocusData: 'Noch keine Verteilung verfügbar.',
      retry: 'Erneut versuchen',
      loadingDashboard: 'Lade dein Dashboard…',
      loadingErrorPrefix: 'Daten konnten nicht geladen werden:',
      metricsOverviewAria: 'Dashboard Kennzahlen',
      minutesUnit: 'min',
      minutesWord: 'Minuten',
      kcalUnit: 'kcal',
      daysUnitLong: 'Tage',
      sourceManual: 'Manuell',
      sourceLearning: 'Lernsession',
      sourceGerman: 'Deutsch',
      sourceEnglish: 'Englisch',
      sourceMath: 'Mathematik',
      weeklyGoalLabel: 'Minuten',
      effortLabel: 'Anstrengung',
      logSessionButton: 'Lernsession eintragen',
      logSessionTitle: 'Lernsession eintragen',
      logSessionSubtitle: 'Wie lange hast du heute gelernt?',
      logDurationLabel: 'Lernzeit',
      logDurationPlaceholder: 'z. B. 30',
      logDateLabel: 'Datum',
      logSourceLabel: 'Fach',
      logEffortLabel: 'Anstrengung (optional)',
      logEffortPlaceholder: '1 bis 10',
      logNotesLabel: 'Notiz (optional)',
      logNotesPlaceholder: 'Was hast du gelernt?',
      saveSession: 'Session speichern',
      cancel: 'Abbrechen',
      closeForm: 'Formular schließen',
      logFirstSession: 'Erste Lernsession eintragen',
      checkInPrompt: 'Du hast heute noch nichts eingetragen — wie lange hast du gelernt?',
      openFullForm: 'Vollständiges Formular',
      dismissBanner: 'Später',
      loggingDurationInvalid: 'Bitte gib eine gültige Lernzeit zwischen 1 und 600 Minuten ein.',
      loggingSaveError: 'Die Lernsession konnte nicht gespeichert werden. Bitte versuche es erneut.',
      sidebarCollapse: 'Sidebar einklappen',
      sidebarExpand: 'Sidebar ausklappen',
      dashboardRedesignHint: 'Das Dashboard wird gerade neu gestaltet. Schau bald wieder vorbei.',
    },
    settings: {
      title: '⚙️ Einstellungen',
      subtitle: 'Theme und Dashboard-Präferenzen werden in user_settings gespeichert.',
      displayTitle: 'Darstellung',
      loadingTheme: 'Lade Theme-Einstellungen…',
      dashboardGoalTitle: 'Dashboard-Ziel',
      dashboardGoalHint: 'Minutenziel pro Woche (30-600) für die Fortschrittsanzeige.',
      save: 'Speichern',
      saved: 'Gespeichert.',
      locked: 'Bestätige zuerst deine E-Mail, um Kontoeinstellungen zu ändern.',
      errorPrefix: 'Fehler:',
      themeSystem: 'System',
      themeLight: 'Hell',
      themeDark: 'Dunkel',
      securityTitle: 'Sicherheit',
      securityHint: 'Ändere dein Passwort. Mindestanforderung: 8 Zeichen und mindestens eine Zahl.',
      accountEmail: 'Konto',
      newPassword: 'Neues Passwort',
      confirmPassword: 'Passwort bestätigen',
      changePassword: 'Passwort ändern',
      passwordSaved: 'Passwort erfolgreich geändert.',
      passwordMinLength: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
      passwordNeedsNumber: 'Das Passwort muss mindestens eine Zahl enthalten.',
      passwordMismatch: 'Passwort und Bestätigung stimmen nicht überein.',
    },
    zenoPage: {
      kicker: 'Zeno Focus',
      title: 'Insights & Empfehlungen',
      subtitle: 'Dein Coach-Bereich mit klaren Empfehlungen für die ZP10-Vorbereitung.',
      loading: 'Zeno lädt deine Insights…',
      errorPrefix: 'Insights konnten nicht geladen werden:',
      retry: 'Erneut versuchen',
      briefingTitle: 'Coach-Briefing',
      focusTitle: 'Fokus-Verteilung',
      noFocusData: 'Noch keine Fokus-Verteilung verfügbar.',
      recommendationStartA: 'Starte mit einer ersten Session, damit Zeno dir personalisierte Empfehlungen liefern kann.',
      recommendationStartB: 'Erfasse Dauer und Anstrengung in jeder Session für präzisere Lern-Insights.',
      recommendationGoal: 'Dir fehlen {minutes} Minuten bis zu deinem Wochenziel.',
      recommendationGoalDone: 'Stark! Dein Wochenziel ist erreicht. Halte die Lernroutine für die nächste Woche stabil.',
      recommendationEffort: 'Dein mittlerer Anstrengungswert ist niedrig. Plane 1-2 fokussierte Deep-Work Sessions ein.',
      recommendationStreak: 'Baue eine Streak auf: schon 20 Minuten pro Tag verbessern die Konsistenz deutlich.',
    },
    zenoCoach: {
      initialMessageA: 'Hi! Ich bin Zeno, dein Lerncoach für die ZP10. Schreibe eine Antwort oder lade eine Aufgabe hoch.',
      initialMessageB: 'Kannst du meine Argumentation prüfen?',
      initialMessageC: 'Klar. Ich orientiere mich am ZP10-Raster und gebe dir strukturiertes Feedback zu Inhalt, Sprache und Aufbau.',
      typingAria: 'Zeno analysiert',
      mockReply: 'Danke! Zeno ist aktuell in Entwicklung. Sobald die Anbindung live ist, bekommst du hier direktes Feedback.',
      statusOnline: 'Online',
      kicker: 'Dein Lerncoach · ZP10',
      subtitle: 'Der Chat ist als Vorschau verfügbar. Die automatische Auswertung folgt bald.',
      inDevelopment: 'In Entwicklung',
      chatAria: 'Chat mit Zeno',
      attachmentsLabel: 'Anhänge:',
      attachmentsAria: 'Dateien oder Bilder anhängen',
      attachmentsButton: 'Datei oder Bild anhängen',
      inputPlaceholder: 'Schreibe an Zeno… (Enter zum Senden)',
      inputAria: 'Nachricht an Zeno',
      sendAria: 'Nachricht senden',
      disclaimer: 'In Entwicklung · Noch keine KI-Anbindung · Anhänge werden lokal nicht gespeichert',
    },
    placeholders: {
      inDevelopment: 'In Entwicklung',
      germanTitle: '📝 Deutsch',
      germanDescription: 'Dieser Bereich wird gerade aufgebaut. Bald findest du hier strukturierte Aufgaben für Deutsch.',
      englishTitle: '🌍 Englisch',
      englishDescription: 'Dieser Bereich wird gerade aufgebaut. Bald findest du hier strukturierte Aufgaben für Englisch.',
      mathTitle: '📐 Mathematik',
      mathDescription: 'Dieser Bereich wird gerade aufgebaut. Bald findest du hier strukturierte Aufgaben für Mathematik.',
      progressTitle: '📈 Fortschritt',
      progressDescription: 'Dieser Bereich wird gerade aufgebaut. Bald siehst du hier deinen Lernfortschritt im Zeitverlauf.',
    },
  },
  en: {
    nav: {
      how: 'How it works',
      subjects: 'Subjects',
      aiFeedback: 'Zeno',
      faq: 'FAQ',
      signIn: 'Sign in',
      themeToggle: 'Toggle dark mode',
    },
    hero: {
      h1a: 'Write. Learn.',
      h1b: 'Pass.',
      sub: 'Practice ZP10 tasks and get honest feedback from Zeno – your personal learning coach who knows exactly how ZP10 is graded.',
      cta: 'Get started for free →',
      learnMore: 'Learn more',
      demoTask: 'German · Argumentation · Task 2',
      demoStatus: 'Zeno has evaluated',
      demoTagThesis: '✓ Clear thesis',
      demoTagEvidence: '✓ Text evidence used',
      demoTagCounter: '↑ Counter-arguments missing',
    },
    how: {
      label: 'Process',
      title: 'Three steps to a better grade',
      sub: 'No memorizing. No guessing. Real feedback on your answers.',
      s1title: 'Work on a task',
      s1text: 'Choose a subject and an exam-style task. Write your answer directly in the app – just like in the real exam.',
      s2title: 'AI evaluates your answer',
      s2text: 'Our AI compares your answer to the official ZP10 grading rubric and gives you a score – transparent and traceable.',
      s3title: 'Improve strategically',
      s3text: 'You see exactly where you\'re strong and what\'s missing. With each practice session, feedback gets sharper – your progress is tracked long-term.',
    },
    subjects: {
      label: 'Subjects',
      title: 'All three ZP10 subjects',
      sub: 'For Gymnasium, Realschule, and Hauptschule – with tasks adapted to your exam profile.',
      deSub: 'Analyze texts, argue, take a stance – with individual feedback on structure, evidence, and language.',
      mathSub: 'Functions, geometry, probability – step-by-step hints and explanations for every calculation path.',
      enSub: 'Reading, Listening, Comment – feedback on your English texts including grammar and vocabulary tips.',
    },
    ki: {
      label: 'Your learning coach',
      title: 'Zeno knows ZP10 inside out.',
      sub: 'No waiting for your teacher. Zeno reads your answer, grades it using the real ZP10 rubric, and tells you exactly what\'s missing.',
      f1title: 'Real point scoring',
      f1text: 'Zeno grades based on the official ZP10 rubric – transparent, traceable, no black box.',
      f2title: 'Strengths & weaknesses',
      f2text: 'You see exactly what worked and what to do better next time – specific, never vague.',
      f3title: 'Progress over time',
      f3text: 'Zeno tracks how you develop – and shows you where you\'ve genuinely improved.',
      mockContent: '»I think social media should be restricted for teens because it creates addiction and negatively affects self-image.«',
      mockLabel1: 'Content & argumentation',
      mockLabel2: 'Language quality',
      mockFeedback: '✓ Thesis clearly stated · Evidence concrete\n↑ Counter-argument missing – show the other side too',
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently asked questions',
      q1: 'Which school types is the app for?',
      a1: 'Currently ZP10 Trainer supports Gymnasium (GYM), Realschule (MSA), and Hauptschule (EESA). More school types like Gesamtschule and Sekundarschule are coming soon.',
      q2: 'Are the tasks real ZP10 exam questions?',
      a2: 'No – we create our own ZP10-style tasks to avoid copyright issues. However, they closely follow the format, topics, and grading criteria of the official exams.',
      q3: 'How exactly does the AI grading work?',
      a3: 'Your answer is sent to an AI model along with the task, a model answer, and the official grading rubric. The model awards points and justifies every decision – transparently and traceably.',
      q4: 'Is the app free?',
      a4: 'During the current beta phase, ZP10 Trainer is free to use. Sign up now and get free access to all practice tasks and AI feedback.',
      q5: 'Is my data stored?',
      a5: 'Yes – to track your learning progress, your answers and results are saved in your account. All data is securely hosted in the EU and not shared with third parties.',
    },
    auth: {
      signIn: 'Sign in',
      signUp: 'Sign up',
      email: 'Email address',
      password: 'Password',
      firstName: 'First name',
      schoolType: 'School type',
      schoolPlaceholder: 'Please select...',
      gym: 'Gymnasium (GYM)',
      msa: 'Realschule (MSA)',
      eesa: 'Hauptschule (EESA)',
      submitSignIn: 'Sign in',
      submitSignUp: 'Create account',
      noAccount: 'No account yet?',
      signUpLink: 'Sign up now',
      hasAccount: 'Already have an account?',
      signInLink: 'Sign in',
      confirmEmailMessage: 'Please confirm your email! Check your inbox and click the confirmation link.',
      goToDashboard: 'Go to Dashboard',
      goToLogin: 'Go to Login',
      forgotPassword: 'Forgot password?',
      forgotPasswordHint: 'Enter your email to receive a reset link.',
      resetPasswordHint: 'If you opened this page from the email link, set your new password now.',
      sendResetMail: 'Send reset email',
      resetMailSent: 'Email sent. Please check your inbox.',
      resetEmailRequired: 'Please enter your email address first.',
      linkExpired: 'The confirmation link has expired. Please sign up again.',
      linkError: 'The confirmation link could not be processed. Please try again.',
      linkErrorGeneric: 'An error occurred during email confirmation.',
      close: 'Close',
    },
    footer: {
      tagline: 'AI-powered ZP10 prep for NRW.',
      appCol: 'App',
      legalCol: 'Legal',
      privacy: 'Privacy policy',
      imprint: 'Imprint',
      terms: 'Terms of use',
      copy: '© 2026 ZP10 Trainer. All rights reserved.',
      disclaimer: 'Not officially affiliated with the state of NRW.',
    },
    dashboard: {
      greeting: 'Hello',
      subtitle: 'Ready for your ZP10 preparation?',
      signOut: 'Sign out',
      fallbackName: 'Learner',
      klasseFallback: 'Class 10',
      nextExam: 'Next Exam',
      daysUnit: 'days',
      examsCompleted: 'Exams completed ✓',
      overallProgress: 'Overall progress',
      subjects: 'Subjects',
      examOverview: 'Exam overview',
      lastActivity: 'Last opened',
      noActivity: 'No activity yet',
      emailNotConfirmed: 'Please confirm your email address to access all content.',
      emailNotConfirmedHint: 'We sent you a confirmation email. Check your spam folder too.',
      resendEmail: 'Resend confirmation email',
      emailResent: 'Email has been resent!',
      emailResendFailed: 'We could not resend the confirmation email. Please try again.',
      contentLocked: 'Confirm your email to unlock this content.',
      quickOverviewTitle: 'Overview',
      quickOverviewDescription: 'Key metrics for your current learning progress.',
      subjectsDescription: 'Choose a subject and continue your training with focus.',
      zenoDescription: 'Start your ZP10 chat with Zeno, upload tasks, and train with structured feedback.',
      zenoHighlights: 'Get concrete hints on argumentation, language, and structure directly in chat.',
      detailsTitle: 'Details',
      detailsDescription: 'Exam planning and your latest learning context at a glance.',
      gotoZenoInsights: 'Open Zeno insights',
      learningThisWeek: 'Learning time this week',
      currentStreak: 'Current streak',
      totalSessions: 'Total sessions',
      totalLearningTime: 'Total learning time',
      weeklyActivityTitle: 'Weekly activity',
      weeklyActivityDescription: 'Your progress over the last 7 days based on your learning sessions.',
      weeklyChartAria: 'Learning minutes per day',
      recentSessionsTitle: 'Recent learning sessions',
      recentSessionsDescription: 'Most recently logged learning sessions from your history.',
      focusTitle: 'Learning focus',
      focusDescription: 'Where you currently invest most of your learning time.',
      noSessionData: 'No learning sessions logged yet.',
      noWeeklySessions: 'No learning session has been logged this week yet.',
      noFocusData: 'No distribution available yet.',
      retry: 'Try again',
      loadingDashboard: 'Loading your dashboard…',
      loadingErrorPrefix: 'Data could not be loaded:',
      metricsOverviewAria: 'Dashboard metrics',
      minutesUnit: 'min',
      minutesWord: 'minutes',
      kcalUnit: 'kcal',
      daysUnitLong: 'days',
      sourceManual: 'Manual',
      sourceLearning: 'Learning session',
      sourceGerman: 'German',
      sourceEnglish: 'English',
      sourceMath: 'Math',
      weeklyGoalLabel: 'minutes',
      effortLabel: 'Effort',
      logSessionButton: 'Log learning session',
      logSessionTitle: 'Log learning session',
      logSessionSubtitle: 'How long did you study today?',
      logDurationLabel: 'Learning time',
      logDurationPlaceholder: 'e.g. 30',
      logDateLabel: 'Date',
      logSourceLabel: 'Subject',
      logEffortLabel: 'Effort (optional)',
      logEffortPlaceholder: '1 to 10',
      logNotesLabel: 'Notes (optional)',
      logNotesPlaceholder: 'What did you study?',
      saveSession: 'Save session',
      cancel: 'Cancel',
      closeForm: 'Close form',
      logFirstSession: 'Log first learning session',
      checkInPrompt: 'You have not logged anything today — how long did you study?',
      openFullForm: 'Open full form',
      dismissBanner: 'Later',
      loggingDurationInvalid: 'Please enter a valid learning time between 1 and 600 minutes.',
      loggingSaveError: 'The learning session could not be saved. Please try again.',
      sidebarCollapse: 'Collapse sidebar',
      sidebarExpand: 'Expand sidebar',
      dashboardRedesignHint: 'The dashboard is being redesigned. Please check back soon.',
    },
    settings: {
      title: '⚙️ Settings',
      subtitle: 'Theme and dashboard preferences are stored in user_settings.',
      displayTitle: 'Appearance',
      loadingTheme: 'Loading theme settings…',
      dashboardGoalTitle: 'Dashboard goal',
      dashboardGoalHint: 'Weekly minute goal (30-600) for progress indicators.',
      save: 'Save',
      saved: 'Saved.',
      locked: 'Please confirm your email before changing account settings.',
      errorPrefix: 'Error:',
      themeSystem: 'System',
      themeLight: 'Light',
      themeDark: 'Dark',
      securityTitle: 'Security',
      securityHint: 'Change your password. Minimum requirement: 8 characters and at least one number.',
      accountEmail: 'Account',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      changePassword: 'Change password',
      passwordSaved: 'Password changed successfully.',
      passwordMinLength: 'Password must be at least 8 characters long.',
      passwordNeedsNumber: 'Password must include at least one number.',
      passwordMismatch: 'Password and confirmation do not match.',
    },
    zenoPage: {
      kicker: 'Zeno Focus',
      title: 'Insights & recommendations',
      subtitle: 'Your coach area with clear recommendations for ZP10 preparation.',
      loading: 'Zeno is loading your insights…',
      errorPrefix: 'Insights could not be loaded:',
      retry: 'Try again',
      briefingTitle: 'Coach briefing',
      focusTitle: 'Focus distribution',
      noFocusData: 'No focus distribution available yet.',
      recommendationStartA: 'Start your first session so Zeno can generate personalized recommendations.',
      recommendationStartB: 'Track duration and effort in each session for more precise learning insights.',
      recommendationGoal: 'You are missing {minutes} minutes to hit your weekly goal.',
      recommendationGoalDone: 'Great! Your weekly goal is reached. Keep the routine steady for next week.',
      recommendationEffort: 'Your average effort score is low. Plan 1-2 focused deep-work sessions.',
      recommendationStreak: 'Build a streak: even 20 minutes per day significantly improves consistency.',
    },
    zenoCoach: {
      initialMessageA: 'Hi! I am Zeno, your learning coach for ZP10. Write an answer or upload a task.',
      initialMessageB: 'Can you review my argumentation?',
      initialMessageC: 'Sure. I follow the ZP10 rubric and provide structured feedback on content, language, and structure.',
      typingAria: 'Zeno is analyzing',
      mockReply: 'Thanks! Zeno is currently in development. Once the integration is live, you will receive direct feedback here.',
      statusOnline: 'Online',
      kicker: 'Your learning coach · ZP10',
      subtitle: 'The chat is available as a preview. Automatic evaluation is coming soon.',
      inDevelopment: 'In development',
      chatAria: 'Chat with Zeno',
      attachmentsLabel: 'Attachments:',
      attachmentsAria: 'Attach files or images',
      attachmentsButton: 'Attach file or image',
      inputPlaceholder: 'Write to Zeno… (press Enter to send)',
      inputAria: 'Message to Zeno',
      sendAria: 'Send message',
      disclaimer: 'In development · No AI integration yet · Attachments are not stored locally',
    },
    placeholders: {
      inDevelopment: 'In development',
      germanTitle: '📝 German',
      germanDescription: 'This area is currently being built. Structured German tasks will be available soon.',
      englishTitle: '🌍 English',
      englishDescription: 'This area is currently being built. Structured English tasks will be available soon.',
      mathTitle: '📐 Math',
      mathDescription: 'This area is currently being built. Structured Math tasks will be available soon.',
      progressTitle: '📈 Progress',
      progressDescription: 'This area is currently being built. You will soon see your learning progress over time.',
    },
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('de')
  const t = translations[lang]
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
